#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "XYZ"
short_name = "staticXYZ"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = "A static site builder written in Python"
description = "A static site builder written in Python"
url = "https://github.com/cole-wilson/xyz"
keywords = "static site jekyll xyz"
license = "none"
latest_build = "0.0.2"
release-notes = "First Release"
latest_release = "0.0.2"


# Resource Setup:
[resources]
icns = ""
data_files = []
modules = [ "toml", "jinja2", "markdown",]
file = "main.py"
no_import = [ "shutil", "os", "glob",]


# Plugin Commands:


# Build Routines:
[build.workflow]

[build.pypi.commands]
xyz = ""

[build.pypi.entry_points]


# Release Routines:


# Other:
[git]


# Thank you for using Sailboat!